/**
 * @file    autoconf.h
 * @brief   Compile-time configuration defines
 * 
 * This file contains compile-time configuration options for the Klipper MCU
 * firmware. It is similar to Klipper's autoconf.h generated by menuconfig.
 * 
 * Modify these defines to configure the firmware for different hardware
 * configurations and feature sets.
 */

#ifndef AUTOCONF_H
#define AUTOCONF_H

#ifdef __cplusplus
extern "C" {
#endif

/* ========== MCU Configuration ========== */

/* Target MCU family */
#define CONFIG_MACH_STM32               1
#define CONFIG_MACH_STM32F4             1
#define CONFIG_MACH_STM32F407           1

/* MCU model string */
#define CONFIG_MCU                      "stm32f407"

/* ========== Clock Configuration ========== */

/* System clock frequency (Hz) */
#define CONFIG_CLOCK_FREQ               168000000

/* High-speed external oscillator frequency (Hz) */
#define CONFIG_CLOCK_REF_FREQ           8000000

/* ========== Memory Configuration ========== */

/* RAM size (bytes) */
#define CONFIG_RAM_SIZE                 (128 * 1024)

/* Flash size (bytes) */
#define CONFIG_FLASH_SIZE               (1024 * 1024)

/* Stack size (bytes) */
#define CONFIG_STACK_SIZE               4096

/* Heap size for memory pool (bytes) */
#define CONFIG_HEAP_SIZE                8192

/* ========== Feature Enables ========== */

/* Enable stepper motor support */
#define CONFIG_HAVE_STEPPER             1

/* Number of stepper motors */
#define CONFIG_STEPPER_COUNT            4

/* Enable GPIO support */
#define CONFIG_HAVE_GPIO                1

/* Enable ADC support */
#define CONFIG_HAVE_ADC                 1

/* Number of ADC channels */
#define CONFIG_ADC_CHANNEL_COUNT        16

/* Enable PWM support */
#define CONFIG_HAVE_PWM                 1

/* Enable serial/UART support */
#define CONFIG_HAVE_SERIAL              1

/* Enable USB support (disabled for MVP) */
#define CONFIG_HAVE_USB                 0

/* Enable SPI support (disabled for MVP) */
#define CONFIG_HAVE_SPI                 0

/* Enable I2C support (disabled for MVP) */
#define CONFIG_HAVE_I2C                 0

/* ========== Serial Configuration ========== */

/* Serial baud rate */
#define CONFIG_SERIAL_BAUD              115200

/* Serial receive buffer size */
#define CONFIG_SERIAL_RX_BUFFER_SIZE    256

/* Serial transmit buffer size */
#define CONFIG_SERIAL_TX_BUFFER_SIZE    256

/* ========== Timer Configuration ========== */

/* System tick frequency (Hz) */
#define CONFIG_SYSTICK_FREQ             1000

/* Step timer frequency (Hz) - for stepper pulse generation */
#define CONFIG_STEP_TIMER_FREQ          1000000

/* ========== Motion Configuration ========== */

/* Maximum number of moves in queue */
#define CONFIG_MOVE_QUEUE_SIZE          32

/* Motion lookahead buffer size */
#define CONFIG_LOOKAHEAD_SIZE           16

/* Enable Cartesian kinematics */
#define CONFIG_KINEMATICS_CARTESIAN     1

/* Enable CoreXY kinematics (disabled for MVP) */
#define CONFIG_KINEMATICS_COREXY        0

/* Enable Delta kinematics (disabled for MVP) */
#define CONFIG_KINEMATICS_DELTA         0

/* ========== Temperature Configuration ========== */

/* Enable heater support */
#define CONFIG_HAVE_HEATER              1

/* Number of heaters */
#define CONFIG_HEATER_COUNT             2

/* Enable fan support */
#define CONFIG_HAVE_FAN                 1

/* Number of fans */
#define CONFIG_FAN_COUNT                2

/* Temperature control update interval (ms) */
#define CONFIG_TEMP_UPDATE_INTERVAL     100

/* ========== G-code Configuration ========== */

/* G-code line buffer size */
#define CONFIG_GCODE_LINE_SIZE          96

/* Enable G-code checksum verification */
#define CONFIG_GCODE_CHECKSUM           0

/* ========== Debug Configuration ========== */

/* Enable debug output */
#ifdef DEBUG
#define CONFIG_DEBUG                    1
#else
#define CONFIG_DEBUG                    0
#endif

/* Enable assert checks */
#define CONFIG_ASSERT                   1

/* Enable watchdog timer */
#define CONFIG_WATCHDOG                 0

/* ========== Build Information ========== */

/* Firmware version string */
#define CONFIG_VERSION                  "0.1.0-mvp"

/* Build date (set by build system) */
#ifndef CONFIG_BUILD_DATE
#define CONFIG_BUILD_DATE               __DATE__
#endif

/* Build time (set by build system) */
#ifndef CONFIG_BUILD_TIME
#define CONFIG_BUILD_TIME               __TIME__
#endif

/* ========== Compatibility Macros ========== */

/* Klipper compatibility - remove __visible macro for MCU build */
#ifdef MCU_BUILD
#define __visible
#endif

/* Klipper compatibility - DECL_* macros (no-op for MCU build) */
#define DECL_COMMAND(func, name)
#define DECL_COMMAND_FLAGS(func, flags, name)
#define DECL_CONSTANT(name, value)
#define DECL_CONSTANT_STR(name, value)
#define DECL_ENUMERATION(name, value)
#define DECL_ENUMERATION_RANGE(name, start, count)
#define DECL_INIT(func)
#define DECL_SHUTDOWN(func)
#define DECL_TASK(func)

#ifdef __cplusplus
}
#endif

#endif /* AUTOCONF_H */
